# DNS模块
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  respect-rules: false
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "rule-set:private_domain,cn_domain"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "time.*.com"
    - "+.market.xiaomi.com"
  default-nameserver:
    - 223.5.5.5
  proxy-server-nameserver:
    - 119.29.29.29
    - system
  nameserver:
    # - 223.5.5.5
    # - 119.29.29.29
    - system

# 节点信息
+proxies:
  - {name: 直连, type: direct}
  - {name: 丢弃, type: reject}

# 策略组
proxy-groups:
  - {name: 默认代理, type: select, proxies: [香港故转, 台湾故转, 狮城故转, 日本故转, 美国故转, 东南亚, 欧洲节点, 小众节点, 全部节点, 自动选择, 直连], icon: "https://raw.githubusercontent.com/fmz200/wool_scripts/main/icons/apps/Macat.png"}
  # - {name: 香港节点, type: select, include-all: true, filter: "(?i)港|hk|hongkong|hong kong", icon: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/icon/color/hk.png"}
  # - {name: 台湾节点, type: select, include-all: true, filter: "(?i)台|tw|taiwan", icon: "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/taiwan(4).png"}
  # - {name: 狮城节点, type: select, include-all: true, filter: "(?i)新加坡|坡|狮城|SG|Singapore", icon: "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/singapore.png"}
  # - {name: 日本节点, type: select, include-all: true, filter: "(?i)日|jp|japan" icon: "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/Japan(2).png"}
  # - {name: 美国节点, type: select, include-all: true, filter: "(?i)美|us|unitedstates|united states", icon: "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/US(2).png"}
  # - {name: 韩国节点, type: select, include-all: true, filter: "(?i)韩|kr|korea|southkorea|south korea", icon: "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/Korea(2).png"}

 
  - {name: 香港故转, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|深|美)).)*$", icon: "https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/HK02.png"}
  - {name: 台湾故转, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?i)台|tw|taiwan", icon: "https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/TW.png"}
  - {name: 狮城故转, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(台|日|韩|深|美)).)*$", icon: "https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/SG.png"}
  - {name: 日本故转, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(日|JP|(?i)Japan))^((?!(港|台|韩|新|美)).)*$", icon: "https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/JP.png"}
  - {name: 美国故转, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(美|US|(?i)States|America))^((?!(港|台|韩|新|日)).)*$", icon: "https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/US.png"}
  - {name: 东南亚, type: select, include-all: true, filter: "(?i)马来|印度尼西亚|印尼|菲律宾|印度|india|缅甸|柬埔寨", icon: "https://raw.githubusercontent.com/fmz200/wool_scripts/main/icons/apps/tajmahal.png"}
  - {name: 欧洲节点, type: select, include-all: true, filter: "(?i)英国|英|uk|unitedkingdom|united kingdom|德国|德|germany|法兰西|法|france|法国|意大利|意|italy|荷兰|荷|netherlands|西班牙|spain|瑞士|瑞典|sweden|switzerland|爱尔兰|ireland|波兰|奥地利|葡萄牙|比利时|爱沙尼亚|芬兰|立陶宛|乌克兰|丹麦|希腊", icon: "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/EuropeanUnion(1).png"}
  - {name: 小众节点, type: select, include-all: true, filter: "(?i)俄罗斯|俄|russia|土耳其|土|turkey|巴西|巴|brazil|阿根廷|argentina|墨西哥|mexico|南非|southafrica|澳大利亚|澳大|australia|新西兰|newzealand|阿联酋|uae|unitedarabemirates|united arab emirates|加拿大|canada|纳米比亚|黎巴嫩|伊朗|哈萨克斯坦|保加利亚", icon: "https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Universal/Airport.png"}

  # - {name: 香港自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|深|美)).)*$"}
  # - {name: 日本自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(日|JP|(?i)Japan))^((?!(港|台|韩|新|美)).)*$" }
  # - {name: 狮城自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(港|台|韩|日|美)).)*$" }
  # - {name: 美国自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(美|US|(?i)States|America))^((?!(港|台|日|韩|新)).)*$"}

  - {name: TikTok, type: select, proxies: [默认代理, 香港故转, 台湾故转, 狮城故转, 日本故转, 美国故转, 全部节点, 直连], icon: "https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/TikTok.png"}
  - {name: YouTube, type: select, proxies: [默认代理, 香港故转, 台湾故转, 狮城故转, 日本故转, 美国故转, 全部节点, 直连], icon: "https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/YouTube.png"}
  - {name: Telegram, type: select, proxies: [默认代理, 香港故转, 台湾故转, 狮城故转, 日本故转, 美国故转, 全部节点, 直连], icon: "https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/Telegram.png"}  
  - {name: Google, type: select, proxies: [默认代理, 香港故转, 台湾故转, 狮城故转, 日本故转, 美国故转, 全部节点, 直连], icon: "https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Google_Suite/Google.png"}
  - {name: ChatGPT, type: select, proxies: [默认代理, 香港故转, 台湾故转, 狮城故转, 日本故转, 美国故转, 全部节点, 直连], icon: "https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/Reddit.png"}
  - {name: GitHub, type: select, proxies: [默认代理, 香港故转, 台湾故转, 狮城故转, 日本故转, 美国故转, 全部节点, 直连], icon: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/icon/qure/color/GitHub.png"}
  - {name: FCM, type: select, proxies: [直连], icon: "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/FishPort.png"} 
  #- {name: OneDrive, type: select, proxies: [默认代理, 香港故转, 台湾故转, 狮城故转, 日本故转, 美国故转, 全部节点, 直连]}
  #- {name: Microsoft, type: select, proxies: [默认代理, 香港故转, 台湾故转, 狮城故转, 日本故转, 美国故转, 全部节点, 直连]}
  #- {name: NETFLIX, type: select, proxies: [默认代理, 香港故转, 台湾故转, 狮城故转, 日本故转, 美国故转, 全部节点, 直连], icon: "https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Universal/Netflix.png"}
  #- {name: PayPal, type: select, proxies: [默认代理, 香港故转, 台湾故转, 狮城故转, 日本故转, 美国故转, 全部节点, 直连], icon: "https://raw.githubusercontent.com/fmz200/wool_scripts/main/icons/apps/Paypal.png"}

  - {name: 隐私拦截, type: select, proxies: [丢弃, 直连], icon: "https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Universal/Reject.orig.png"}
  - {name: 漏网之鱼, type: select, proxies: [默认代理, 香港故转, 台湾故转, 狮城故转, 日本故转, 美国故转, 全部节点, 直连], icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/all.png"}
  - {name: 自动选择, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "^((?!(直连)).)*$", icon: "https://raw.githubusercontent.com/fmz200/wool_scripts/main/icons/apps/Auto.png"}
  - {name: 全部节点, type: select, include-all: true, icon: "https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/global.png"}

rules: 
  - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOSITE,cn))),REJECT
  - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOIP,CN))),REJECT

  - RULE-SET,embylist_domain,直连
  - RULE-SET,banAd_domain,隐私拦截
  - RULE-SET,telegram_ip,Telegram,no-resolve
  - DOMAIN-SUFFIX,googleapis.cn,默认代理
  - RULE-SET,google_ip,Google,no-resolve

  - DOMAIN-SUFFIX,skk.moe,DIRECT
  - DOMAIN-SUFFIX,challenges.cloudflare.com,DIRECT
  - DOMAIN-SUFFIX,edge.microsoft.com,DIRECT
  - DOMAIN-SUFFIX,data.microsoft.com,DIRECT
  - DOMAIN-SUFFIX,microsoftonline.com,DIRECT
  - DOMAIN-SUFFIX,appcenter.ms,DIRECT
  - DOMAIN-SUFFIX,rewardsplatform.microsoft.com,DIRECT
  - DOMAIN-SUFFIX,app-measurement.com,DIRECT
  - DOMAIN-SUFFIX,qichiyu.com,默认代理
  - RULE-SET,private_ip,直连,no-resolve
  - RULE-SET,private_domain,直连
  - RULE-SET,proxylite,默认代理
  - RULE-SET,ai,ChatGPT
  - RULE-SET,github_domain,GitHub
  - RULE-SET,youtube_domain,YouTube
  - RULE-SET,google_domain,Google
  #- RULE-SET,onedrive_domain,OneDrive
  #- RULE-SET,microsoft_domain,Microsoft
  #- RULE-SET,apple_domain,直连
  - RULE-SET,tiktok_domain,TikTok
  - RULE-SET,telegram_domain,Telegram
  #- RULE-SET,netflix_domain,NETFLIX
  #- RULE-SET,paypal_domain,PayPal
  #- RULE-SET,apple_ip,直连
  #- RULE-SET,netflix_ip,NETFLIX
  
  - RULE-SET,geolocation-!cn,默认代理
  - RULE-SET,cn_domain,直连
  - RULE-SET,cn_ip,直连
  - MATCH,漏网之鱼
  
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
  
rule-providers: 
  embylist_domain: { <<: *class, url: "https://raw.githubusercontent.com/wushijujibu/Rules/refs/heads/main/emby_loon.list" }
  banAd_domain: { <<: *class, url: "https://adrules.top/adrules.list" }
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  proxylite: { <<: *class, url: "https://raw.githubusercontent.com/qichiyuhub/rule/refs/heads/main/proxy.list"}
  ai: {  <<: *domain, url: "https://ruleset.ihtw.moe/resources/rules/ai.mrs" }
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  #netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  #paypal_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  #onedrive_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  #microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  #apple_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs"}
  #speedtest_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  tiktok_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  
  private_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"}
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  #netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  #apple_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs"}



